# Generated by Django 6.0.7 on 2026-08-05 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadprodutos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='update_ate',
            new_name='update_at',
        ),
    ]
